// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $contact from "./routes/contact.tsx";
import * as $index from "./routes/index.tsx";
import * as $privacy_policy from "./routes/privacy-policy.tsx";
import * as $unions_slug_ from "./routes/unions/[slug].tsx";
import * as $Toast from "./islands/Toast.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/contact.tsx": $contact,
    "./routes/index.tsx": $index,
    "./routes/privacy-policy.tsx": $privacy_policy,
    "./routes/unions/[slug].tsx": $unions_slug_,
  },
  islands: {
    "./islands/Toast.tsx": $Toast,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
